// Code generated by ent, DO NOT EDIT.

package incomingwebhookevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldEnvironmentID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldProvider, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldMethod, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldPath, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldRequestID, v))
}

// ProviderEventID applies equality check predicate on the "provider_event_id" field. It's identical to ProviderEventIDEQ.
func ProviderEventID(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldProviderEventID, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldBody, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldProvider, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldMethod, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldPath, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldRequestID, v))
}

// ProviderEventIDEQ applies the EQ predicate on the "provider_event_id" field.
func ProviderEventIDEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldProviderEventID, v))
}

// ProviderEventIDNEQ applies the NEQ predicate on the "provider_event_id" field.
func ProviderEventIDNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldProviderEventID, v))
}

// ProviderEventIDIn applies the In predicate on the "provider_event_id" field.
func ProviderEventIDIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldProviderEventID, vs...))
}

// ProviderEventIDNotIn applies the NotIn predicate on the "provider_event_id" field.
func ProviderEventIDNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldProviderEventID, vs...))
}

// ProviderEventIDGT applies the GT predicate on the "provider_event_id" field.
func ProviderEventIDGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldProviderEventID, v))
}

// ProviderEventIDGTE applies the GTE predicate on the "provider_event_id" field.
func ProviderEventIDGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldProviderEventID, v))
}

// ProviderEventIDLT applies the LT predicate on the "provider_event_id" field.
func ProviderEventIDLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldProviderEventID, v))
}

// ProviderEventIDLTE applies the LTE predicate on the "provider_event_id" field.
func ProviderEventIDLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldProviderEventID, v))
}

// ProviderEventIDContains applies the Contains predicate on the "provider_event_id" field.
func ProviderEventIDContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldProviderEventID, v))
}

// ProviderEventIDHasPrefix applies the HasPrefix predicate on the "provider_event_id" field.
func ProviderEventIDHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldProviderEventID, v))
}

// ProviderEventIDHasSuffix applies the HasSuffix predicate on the "provider_event_id" field.
func ProviderEventIDHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldProviderEventID, v))
}

// ProviderEventIDIsNil applies the IsNil predicate on the "provider_event_id" field.
func ProviderEventIDIsNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIsNull(FieldProviderEventID))
}

// ProviderEventIDNotNil applies the NotNil predicate on the "provider_event_id" field.
func ProviderEventIDNotNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotNull(FieldProviderEventID))
}

// ProviderEventIDEqualFold applies the EqualFold predicate on the "provider_event_id" field.
func ProviderEventIDEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldProviderEventID, v))
}

// ProviderEventIDContainsFold applies the ContainsFold predicate on the "provider_event_id" field.
func ProviderEventIDContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldProviderEventID, v))
}

// HeadersIsNil applies the IsNil predicate on the "headers" field.
func HeadersIsNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIsNull(FieldHeaders))
}

// HeadersNotNil applies the NotNil predicate on the "headers" field.
func HeadersNotNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotNull(FieldHeaders))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldHasSuffix(FieldBody, v))
}

// BodyIsNil applies the IsNil predicate on the "body" field.
func BodyIsNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldIsNull(FieldBody))
}

// BodyNotNil applies the NotNil predicate on the "body" field.
func BodyNotNil() predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldNotNull(FieldBody))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.FieldContainsFold(FieldBody, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IncomingWebhookEvent) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IncomingWebhookEvent) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IncomingWebhookEvent) predicate.IncomingWebhookEvent {
	return predicate.IncomingWebhookEvent(sql.NotPredicates(p))
}
