// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/incomingwebhookevent"
	"github.com/flexprice/flexprice/ent/predicate"
)

// IncomingWebhookEventUpdate is the builder for updating IncomingWebhookEvent entities.
type IncomingWebhookEventUpdate struct {
	config
	hooks    []Hook
	mutation *IncomingWebhookEventMutation
}

// Where appends a list predicates to the IncomingWebhookEventUpdate builder.
func (iweu *IncomingWebhookEventUpdate) Where(ps ...predicate.IncomingWebhookEvent) *IncomingWebhookEventUpdate {
	iweu.mutation.Where(ps...)
	return iweu
}

// SetStatus sets the "status" field.
func (iweu *IncomingWebhookEventUpdate) SetStatus(s string) *IncomingWebhookEventUpdate {
	iweu.mutation.SetStatus(s)
	return iweu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (iweu *IncomingWebhookEventUpdate) SetNillableStatus(s *string) *IncomingWebhookEventUpdate {
	if s != nil {
		iweu.SetStatus(*s)
	}
	return iweu
}

// SetUpdatedAt sets the "updated_at" field.
func (iweu *IncomingWebhookEventUpdate) SetUpdatedAt(t time.Time) *IncomingWebhookEventUpdate {
	iweu.mutation.SetUpdatedAt(t)
	return iweu
}

// SetUpdatedBy sets the "updated_by" field.
func (iweu *IncomingWebhookEventUpdate) SetUpdatedBy(s string) *IncomingWebhookEventUpdate {
	iweu.mutation.SetUpdatedBy(s)
	return iweu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (iweu *IncomingWebhookEventUpdate) SetNillableUpdatedBy(s *string) *IncomingWebhookEventUpdate {
	if s != nil {
		iweu.SetUpdatedBy(*s)
	}
	return iweu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (iweu *IncomingWebhookEventUpdate) ClearUpdatedBy() *IncomingWebhookEventUpdate {
	iweu.mutation.ClearUpdatedBy()
	return iweu
}

// SetProviderEventID sets the "provider_event_id" field.
func (iweu *IncomingWebhookEventUpdate) SetProviderEventID(s string) *IncomingWebhookEventUpdate {
	iweu.mutation.SetProviderEventID(s)
	return iweu
}

// SetNillableProviderEventID sets the "provider_event_id" field if the given value is not nil.
func (iweu *IncomingWebhookEventUpdate) SetNillableProviderEventID(s *string) *IncomingWebhookEventUpdate {
	if s != nil {
		iweu.SetProviderEventID(*s)
	}
	return iweu
}

// ClearProviderEventID clears the value of the "provider_event_id" field.
func (iweu *IncomingWebhookEventUpdate) ClearProviderEventID() *IncomingWebhookEventUpdate {
	iweu.mutation.ClearProviderEventID()
	return iweu
}

// Mutation returns the IncomingWebhookEventMutation object of the builder.
func (iweu *IncomingWebhookEventUpdate) Mutation() *IncomingWebhookEventMutation {
	return iweu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iweu *IncomingWebhookEventUpdate) Save(ctx context.Context) (int, error) {
	iweu.defaults()
	return withHooks(ctx, iweu.sqlSave, iweu.mutation, iweu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iweu *IncomingWebhookEventUpdate) SaveX(ctx context.Context) int {
	affected, err := iweu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iweu *IncomingWebhookEventUpdate) Exec(ctx context.Context) error {
	_, err := iweu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iweu *IncomingWebhookEventUpdate) ExecX(ctx context.Context) {
	if err := iweu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iweu *IncomingWebhookEventUpdate) defaults() {
	if _, ok := iweu.mutation.UpdatedAt(); !ok {
		v := incomingwebhookevent.UpdateDefaultUpdatedAt()
		iweu.mutation.SetUpdatedAt(v)
	}
}

func (iweu *IncomingWebhookEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(incomingwebhookevent.Table, incomingwebhookevent.Columns, sqlgraph.NewFieldSpec(incomingwebhookevent.FieldID, field.TypeString))
	if ps := iweu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iweu.mutation.Status(); ok {
		_spec.SetField(incomingwebhookevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := iweu.mutation.UpdatedAt(); ok {
		_spec.SetField(incomingwebhookevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if iweu.mutation.CreatedByCleared() {
		_spec.ClearField(incomingwebhookevent.FieldCreatedBy, field.TypeString)
	}
	if value, ok := iweu.mutation.UpdatedBy(); ok {
		_spec.SetField(incomingwebhookevent.FieldUpdatedBy, field.TypeString, value)
	}
	if iweu.mutation.UpdatedByCleared() {
		_spec.ClearField(incomingwebhookevent.FieldUpdatedBy, field.TypeString)
	}
	if iweu.mutation.EnvironmentIDCleared() {
		_spec.ClearField(incomingwebhookevent.FieldEnvironmentID, field.TypeString)
	}
	if iweu.mutation.RequestIDCleared() {
		_spec.ClearField(incomingwebhookevent.FieldRequestID, field.TypeString)
	}
	if value, ok := iweu.mutation.ProviderEventID(); ok {
		_spec.SetField(incomingwebhookevent.FieldProviderEventID, field.TypeString, value)
	}
	if iweu.mutation.ProviderEventIDCleared() {
		_spec.ClearField(incomingwebhookevent.FieldProviderEventID, field.TypeString)
	}
	if iweu.mutation.HeadersCleared() {
		_spec.ClearField(incomingwebhookevent.FieldHeaders, field.TypeJSON)
	}
	if iweu.mutation.BodyCleared() {
		_spec.ClearField(incomingwebhookevent.FieldBody, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iweu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{incomingwebhookevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iweu.mutation.done = true
	return n, nil
}

// IncomingWebhookEventUpdateOne is the builder for updating a single IncomingWebhookEvent entity.
type IncomingWebhookEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IncomingWebhookEventMutation
}

// SetStatus sets the "status" field.
func (iweuo *IncomingWebhookEventUpdateOne) SetStatus(s string) *IncomingWebhookEventUpdateOne {
	iweuo.mutation.SetStatus(s)
	return iweuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (iweuo *IncomingWebhookEventUpdateOne) SetNillableStatus(s *string) *IncomingWebhookEventUpdateOne {
	if s != nil {
		iweuo.SetStatus(*s)
	}
	return iweuo
}

// SetUpdatedAt sets the "updated_at" field.
func (iweuo *IncomingWebhookEventUpdateOne) SetUpdatedAt(t time.Time) *IncomingWebhookEventUpdateOne {
	iweuo.mutation.SetUpdatedAt(t)
	return iweuo
}

// SetUpdatedBy sets the "updated_by" field.
func (iweuo *IncomingWebhookEventUpdateOne) SetUpdatedBy(s string) *IncomingWebhookEventUpdateOne {
	iweuo.mutation.SetUpdatedBy(s)
	return iweuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (iweuo *IncomingWebhookEventUpdateOne) SetNillableUpdatedBy(s *string) *IncomingWebhookEventUpdateOne {
	if s != nil {
		iweuo.SetUpdatedBy(*s)
	}
	return iweuo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (iweuo *IncomingWebhookEventUpdateOne) ClearUpdatedBy() *IncomingWebhookEventUpdateOne {
	iweuo.mutation.ClearUpdatedBy()
	return iweuo
}

// SetProviderEventID sets the "provider_event_id" field.
func (iweuo *IncomingWebhookEventUpdateOne) SetProviderEventID(s string) *IncomingWebhookEventUpdateOne {
	iweuo.mutation.SetProviderEventID(s)
	return iweuo
}

// SetNillableProviderEventID sets the "provider_event_id" field if the given value is not nil.
func (iweuo *IncomingWebhookEventUpdateOne) SetNillableProviderEventID(s *string) *IncomingWebhookEventUpdateOne {
	if s != nil {
		iweuo.SetProviderEventID(*s)
	}
	return iweuo
}

// ClearProviderEventID clears the value of the "provider_event_id" field.
func (iweuo *IncomingWebhookEventUpdateOne) ClearProviderEventID() *IncomingWebhookEventUpdateOne {
	iweuo.mutation.ClearProviderEventID()
	return iweuo
}

// Mutation returns the IncomingWebhookEventMutation object of the builder.
func (iweuo *IncomingWebhookEventUpdateOne) Mutation() *IncomingWebhookEventMutation {
	return iweuo.mutation
}

// Where appends a list predicates to the IncomingWebhookEventUpdate builder.
func (iweuo *IncomingWebhookEventUpdateOne) Where(ps ...predicate.IncomingWebhookEvent) *IncomingWebhookEventUpdateOne {
	iweuo.mutation.Where(ps...)
	return iweuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iweuo *IncomingWebhookEventUpdateOne) Select(field string, fields ...string) *IncomingWebhookEventUpdateOne {
	iweuo.fields = append([]string{field}, fields...)
	return iweuo
}

// Save executes the query and returns the updated IncomingWebhookEvent entity.
func (iweuo *IncomingWebhookEventUpdateOne) Save(ctx context.Context) (*IncomingWebhookEvent, error) {
	iweuo.defaults()
	return withHooks(ctx, iweuo.sqlSave, iweuo.mutation, iweuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iweuo *IncomingWebhookEventUpdateOne) SaveX(ctx context.Context) *IncomingWebhookEvent {
	node, err := iweuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iweuo *IncomingWebhookEventUpdateOne) Exec(ctx context.Context) error {
	_, err := iweuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iweuo *IncomingWebhookEventUpdateOne) ExecX(ctx context.Context) {
	if err := iweuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iweuo *IncomingWebhookEventUpdateOne) defaults() {
	if _, ok := iweuo.mutation.UpdatedAt(); !ok {
		v := incomingwebhookevent.UpdateDefaultUpdatedAt()
		iweuo.mutation.SetUpdatedAt(v)
	}
}

func (iweuo *IncomingWebhookEventUpdateOne) sqlSave(ctx context.Context) (_node *IncomingWebhookEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(incomingwebhookevent.Table, incomingwebhookevent.Columns, sqlgraph.NewFieldSpec(incomingwebhookevent.FieldID, field.TypeString))
	id, ok := iweuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IncomingWebhookEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iweuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, incomingwebhookevent.FieldID)
		for _, f := range fields {
			if !incomingwebhookevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != incomingwebhookevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iweuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iweuo.mutation.Status(); ok {
		_spec.SetField(incomingwebhookevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := iweuo.mutation.UpdatedAt(); ok {
		_spec.SetField(incomingwebhookevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if iweuo.mutation.CreatedByCleared() {
		_spec.ClearField(incomingwebhookevent.FieldCreatedBy, field.TypeString)
	}
	if value, ok := iweuo.mutation.UpdatedBy(); ok {
		_spec.SetField(incomingwebhookevent.FieldUpdatedBy, field.TypeString, value)
	}
	if iweuo.mutation.UpdatedByCleared() {
		_spec.ClearField(incomingwebhookevent.FieldUpdatedBy, field.TypeString)
	}
	if iweuo.mutation.EnvironmentIDCleared() {
		_spec.ClearField(incomingwebhookevent.FieldEnvironmentID, field.TypeString)
	}
	if iweuo.mutation.RequestIDCleared() {
		_spec.ClearField(incomingwebhookevent.FieldRequestID, field.TypeString)
	}
	if value, ok := iweuo.mutation.ProviderEventID(); ok {
		_spec.SetField(incomingwebhookevent.FieldProviderEventID, field.TypeString, value)
	}
	if iweuo.mutation.ProviderEventIDCleared() {
		_spec.ClearField(incomingwebhookevent.FieldProviderEventID, field.TypeString)
	}
	if iweuo.mutation.HeadersCleared() {
		_spec.ClearField(incomingwebhookevent.FieldHeaders, field.TypeJSON)
	}
	if iweuo.mutation.BodyCleared() {
		_spec.ClearField(incomingwebhookevent.FieldBody, field.TypeString)
	}
	_node = &IncomingWebhookEvent{config: iweuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iweuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{incomingwebhookevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iweuo.mutation.done = true
	return _node, nil
}
