// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/incomingwebhookevent"
)

// IncomingWebhookEvent is the model entity for the IncomingWebhookEvent schema.
type IncomingWebhookEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// ProviderEventID holds the value of the "provider_event_id" field.
	ProviderEventID string `json:"provider_event_id,omitempty"`
	// Headers holds the value of the "headers" field.
	Headers map[string][]string `json:"headers,omitempty"`
	// Body holds the value of the "body" field.
	Body         string `json:"body,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IncomingWebhookEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case incomingwebhookevent.FieldHeaders:
			values[i] = new([]byte)
		case incomingwebhookevent.FieldID, incomingwebhookevent.FieldTenantID, incomingwebhookevent.FieldStatus, incomingwebhookevent.FieldCreatedBy, incomingwebhookevent.FieldUpdatedBy, incomingwebhookevent.FieldEnvironmentID, incomingwebhookevent.FieldProvider, incomingwebhookevent.FieldMethod, incomingwebhookevent.FieldPath, incomingwebhookevent.FieldRequestID, incomingwebhookevent.FieldProviderEventID, incomingwebhookevent.FieldBody:
			values[i] = new(sql.NullString)
		case incomingwebhookevent.FieldCreatedAt, incomingwebhookevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IncomingWebhookEvent fields.
func (iwe *IncomingWebhookEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case incomingwebhookevent.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				iwe.ID = value.String
			}
		case incomingwebhookevent.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				iwe.TenantID = value.String
			}
		case incomingwebhookevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				iwe.Status = value.String
			}
		case incomingwebhookevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				iwe.CreatedAt = value.Time
			}
		case incomingwebhookevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				iwe.UpdatedAt = value.Time
			}
		case incomingwebhookevent.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				iwe.CreatedBy = value.String
			}
		case incomingwebhookevent.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				iwe.UpdatedBy = value.String
			}
		case incomingwebhookevent.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				iwe.EnvironmentID = value.String
			}
		case incomingwebhookevent.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				iwe.Provider = value.String
			}
		case incomingwebhookevent.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				iwe.Method = value.String
			}
		case incomingwebhookevent.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				iwe.Path = value.String
			}
		case incomingwebhookevent.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				iwe.RequestID = value.String
			}
		case incomingwebhookevent.FieldProviderEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_event_id", values[i])
			} else if value.Valid {
				iwe.ProviderEventID = value.String
			}
		case incomingwebhookevent.FieldHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &iwe.Headers); err != nil {
					return fmt.Errorf("unmarshal field headers: %w", err)
				}
			}
		case incomingwebhookevent.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				iwe.Body = value.String
			}
		default:
			iwe.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IncomingWebhookEvent.
// This includes values selected through modifiers, order, etc.
func (iwe *IncomingWebhookEvent) Value(name string) (ent.Value, error) {
	return iwe.selectValues.Get(name)
}

// Update returns a builder for updating this IncomingWebhookEvent.
// Note that you need to call IncomingWebhookEvent.Unwrap() before calling this method if this IncomingWebhookEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (iwe *IncomingWebhookEvent) Update() *IncomingWebhookEventUpdateOne {
	return NewIncomingWebhookEventClient(iwe.config).UpdateOne(iwe)
}

// Unwrap unwraps the IncomingWebhookEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (iwe *IncomingWebhookEvent) Unwrap() *IncomingWebhookEvent {
	_tx, ok := iwe.config.driver.(*txDriver)
	if !ok {
		panic("ent: IncomingWebhookEvent is not a transactional entity")
	}
	iwe.config.driver = _tx.drv
	return iwe
}

// String implements the fmt.Stringer.
func (iwe *IncomingWebhookEvent) String() string {
	var builder strings.Builder
	builder.WriteString("IncomingWebhookEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", iwe.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(iwe.TenantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(iwe.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(iwe.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(iwe.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(iwe.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(iwe.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(iwe.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(iwe.Provider)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(iwe.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(iwe.Path)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(iwe.RequestID)
	builder.WriteString(", ")
	builder.WriteString("provider_event_id=")
	builder.WriteString(iwe.ProviderEventID)
	builder.WriteString(", ")
	builder.WriteString("headers=")
	builder.WriteString(fmt.Sprintf("%v", iwe.Headers))
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(iwe.Body)
	builder.WriteByte(')')
	return builder.String()
}

// IncomingWebhookEvents is a parsable slice of IncomingWebhookEvent.
type IncomingWebhookEvents []*IncomingWebhookEvent
