// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/incomingwebhookevent"
)

// IncomingWebhookEventCreate is the builder for creating a IncomingWebhookEvent entity.
type IncomingWebhookEventCreate struct {
	config
	mutation *IncomingWebhookEventMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (iwec *IncomingWebhookEventCreate) SetTenantID(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetTenantID(s)
	return iwec
}

// SetStatus sets the "status" field.
func (iwec *IncomingWebhookEventCreate) SetStatus(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetStatus(s)
	return iwec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (iwec *IncomingWebhookEventCreate) SetNillableStatus(s *string) *IncomingWebhookEventCreate {
	if s != nil {
		iwec.SetStatus(*s)
	}
	return iwec
}

// SetCreatedAt sets the "created_at" field.
func (iwec *IncomingWebhookEventCreate) SetCreatedAt(t time.Time) *IncomingWebhookEventCreate {
	iwec.mutation.SetCreatedAt(t)
	return iwec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iwec *IncomingWebhookEventCreate) SetNillableCreatedAt(t *time.Time) *IncomingWebhookEventCreate {
	if t != nil {
		iwec.SetCreatedAt(*t)
	}
	return iwec
}

// SetUpdatedAt sets the "updated_at" field.
func (iwec *IncomingWebhookEventCreate) SetUpdatedAt(t time.Time) *IncomingWebhookEventCreate {
	iwec.mutation.SetUpdatedAt(t)
	return iwec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (iwec *IncomingWebhookEventCreate) SetNillableUpdatedAt(t *time.Time) *IncomingWebhookEventCreate {
	if t != nil {
		iwec.SetUpdatedAt(*t)
	}
	return iwec
}

// SetCreatedBy sets the "created_by" field.
func (iwec *IncomingWebhookEventCreate) SetCreatedBy(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetCreatedBy(s)
	return iwec
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (iwec *IncomingWebhookEventCreate) SetNillableCreatedBy(s *string) *IncomingWebhookEventCreate {
	if s != nil {
		iwec.SetCreatedBy(*s)
	}
	return iwec
}

// SetUpdatedBy sets the "updated_by" field.
func (iwec *IncomingWebhookEventCreate) SetUpdatedBy(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetUpdatedBy(s)
	return iwec
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (iwec *IncomingWebhookEventCreate) SetNillableUpdatedBy(s *string) *IncomingWebhookEventCreate {
	if s != nil {
		iwec.SetUpdatedBy(*s)
	}
	return iwec
}

// SetEnvironmentID sets the "environment_id" field.
func (iwec *IncomingWebhookEventCreate) SetEnvironmentID(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetEnvironmentID(s)
	return iwec
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (iwec *IncomingWebhookEventCreate) SetNillableEnvironmentID(s *string) *IncomingWebhookEventCreate {
	if s != nil {
		iwec.SetEnvironmentID(*s)
	}
	return iwec
}

// SetProvider sets the "provider" field.
func (iwec *IncomingWebhookEventCreate) SetProvider(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetProvider(s)
	return iwec
}

// SetMethod sets the "method" field.
func (iwec *IncomingWebhookEventCreate) SetMethod(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetMethod(s)
	return iwec
}

// SetPath sets the "path" field.
func (iwec *IncomingWebhookEventCreate) SetPath(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetPath(s)
	return iwec
}

// SetRequestID sets the "request_id" field.
func (iwec *IncomingWebhookEventCreate) SetRequestID(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetRequestID(s)
	return iwec
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (iwec *IncomingWebhookEventCreate) SetNillableRequestID(s *string) *IncomingWebhookEventCreate {
	if s != nil {
		iwec.SetRequestID(*s)
	}
	return iwec
}

// SetProviderEventID sets the "provider_event_id" field.
func (iwec *IncomingWebhookEventCreate) SetProviderEventID(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetProviderEventID(s)
	return iwec
}

// SetNillableProviderEventID sets the "provider_event_id" field if the given value is not nil.
func (iwec *IncomingWebhookEventCreate) SetNillableProviderEventID(s *string) *IncomingWebhookEventCreate {
	if s != nil {
		iwec.SetProviderEventID(*s)
	}
	return iwec
}

// SetHeaders sets the "headers" field.
func (iwec *IncomingWebhookEventCreate) SetHeaders(m map[string][]string) *IncomingWebhookEventCreate {
	iwec.mutation.SetHeaders(m)
	return iwec
}

// SetBody sets the "body" field.
func (iwec *IncomingWebhookEventCreate) SetBody(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetBody(s)
	return iwec
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (iwec *IncomingWebhookEventCreate) SetNillableBody(s *string) *IncomingWebhookEventCreate {
	if s != nil {
		iwec.SetBody(*s)
	}
	return iwec
}

// SetID sets the "id" field.
func (iwec *IncomingWebhookEventCreate) SetID(s string) *IncomingWebhookEventCreate {
	iwec.mutation.SetID(s)
	return iwec
}

// Mutation returns the IncomingWebhookEventMutation object of the builder.
func (iwec *IncomingWebhookEventCreate) Mutation() *IncomingWebhookEventMutation {
	return iwec.mutation
}

// Save creates the IncomingWebhookEvent in the database.
func (iwec *IncomingWebhookEventCreate) Save(ctx context.Context) (*IncomingWebhookEvent, error) {
	iwec.defaults()
	return withHooks(ctx, iwec.sqlSave, iwec.mutation, iwec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (iwec *IncomingWebhookEventCreate) SaveX(ctx context.Context) *IncomingWebhookEvent {
	v, err := iwec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iwec *IncomingWebhookEventCreate) Exec(ctx context.Context) error {
	_, err := iwec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iwec *IncomingWebhookEventCreate) ExecX(ctx context.Context) {
	if err := iwec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iwec *IncomingWebhookEventCreate) defaults() {
	if _, ok := iwec.mutation.Status(); !ok {
		v := incomingwebhookevent.DefaultStatus
		iwec.mutation.SetStatus(v)
	}
	if _, ok := iwec.mutation.CreatedAt(); !ok {
		v := incomingwebhookevent.DefaultCreatedAt()
		iwec.mutation.SetCreatedAt(v)
	}
	if _, ok := iwec.mutation.UpdatedAt(); !ok {
		v := incomingwebhookevent.DefaultUpdatedAt()
		iwec.mutation.SetUpdatedAt(v)
	}
	if _, ok := iwec.mutation.EnvironmentID(); !ok {
		v := incomingwebhookevent.DefaultEnvironmentID
		iwec.mutation.SetEnvironmentID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iwec *IncomingWebhookEventCreate) check() error {
	if _, ok := iwec.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "IncomingWebhookEvent.tenant_id"`)}
	}
	if v, ok := iwec.mutation.TenantID(); ok {
		if err := incomingwebhookevent.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "IncomingWebhookEvent.tenant_id": %w`, err)}
		}
	}
	if _, ok := iwec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IncomingWebhookEvent.status"`)}
	}
	if _, ok := iwec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IncomingWebhookEvent.created_at"`)}
	}
	if _, ok := iwec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IncomingWebhookEvent.updated_at"`)}
	}
	if _, ok := iwec.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "IncomingWebhookEvent.provider"`)}
	}
	if v, ok := iwec.mutation.Provider(); ok {
		if err := incomingwebhookevent.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "IncomingWebhookEvent.provider": %w`, err)}
		}
	}
	if _, ok := iwec.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "IncomingWebhookEvent.method"`)}
	}
	if v, ok := iwec.mutation.Method(); ok {
		if err := incomingwebhookevent.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "IncomingWebhookEvent.method": %w`, err)}
		}
	}
	if _, ok := iwec.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "IncomingWebhookEvent.path"`)}
	}
	if v, ok := iwec.mutation.Path(); ok {
		if err := incomingwebhookevent.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "IncomingWebhookEvent.path": %w`, err)}
		}
	}
	return nil
}

func (iwec *IncomingWebhookEventCreate) sqlSave(ctx context.Context) (*IncomingWebhookEvent, error) {
	if err := iwec.check(); err != nil {
		return nil, err
	}
	_node, _spec := iwec.createSpec()
	if err := sqlgraph.CreateNode(ctx, iwec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected IncomingWebhookEvent.ID type: %T", _spec.ID.Value)
		}
	}
	iwec.mutation.id = &_node.ID
	iwec.mutation.done = true
	return _node, nil
}

func (iwec *IncomingWebhookEventCreate) createSpec() (*IncomingWebhookEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &IncomingWebhookEvent{config: iwec.config}
		_spec = sqlgraph.NewCreateSpec(incomingwebhookevent.Table, sqlgraph.NewFieldSpec(incomingwebhookevent.FieldID, field.TypeString))
	)
	if id, ok := iwec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := iwec.mutation.TenantID(); ok {
		_spec.SetField(incomingwebhookevent.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := iwec.mutation.Status(); ok {
		_spec.SetField(incomingwebhookevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := iwec.mutation.CreatedAt(); ok {
		_spec.SetField(incomingwebhookevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := iwec.mutation.UpdatedAt(); ok {
		_spec.SetField(incomingwebhookevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := iwec.mutation.CreatedBy(); ok {
		_spec.SetField(incomingwebhookevent.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := iwec.mutation.UpdatedBy(); ok {
		_spec.SetField(incomingwebhookevent.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := iwec.mutation.EnvironmentID(); ok {
		_spec.SetField(incomingwebhookevent.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := iwec.mutation.Provider(); ok {
		_spec.SetField(incomingwebhookevent.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := iwec.mutation.Method(); ok {
		_spec.SetField(incomingwebhookevent.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := iwec.mutation.Path(); ok {
		_spec.SetField(incomingwebhookevent.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := iwec.mutation.RequestID(); ok {
		_spec.SetField(incomingwebhookevent.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := iwec.mutation.ProviderEventID(); ok {
		_spec.SetField(incomingwebhookevent.FieldProviderEventID, field.TypeString, value)
		_node.ProviderEventID = value
	}
	if value, ok := iwec.mutation.Headers(); ok {
		_spec.SetField(incomingwebhookevent.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := iwec.mutation.Body(); ok {
		_spec.SetField(incomingwebhookevent.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	return _node, _spec
}

// IncomingWebhookEventCreateBulk is the builder for creating many IncomingWebhookEvent entities in bulk.
type IncomingWebhookEventCreateBulk struct {
	config
	err      error
	builders []*IncomingWebhookEventCreate
}

// Save creates the IncomingWebhookEvent entities in the database.
func (iwecb *IncomingWebhookEventCreateBulk) Save(ctx context.Context) ([]*IncomingWebhookEvent, error) {
	if iwecb.err != nil {
		return nil, iwecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(iwecb.builders))
	nodes := make([]*IncomingWebhookEvent, len(iwecb.builders))
	mutators := make([]Mutator, len(iwecb.builders))
	for i := range iwecb.builders {
		func(i int, root context.Context) {
			builder := iwecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IncomingWebhookEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, iwecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, iwecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, iwecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (iwecb *IncomingWebhookEventCreateBulk) SaveX(ctx context.Context) []*IncomingWebhookEvent {
	v, err := iwecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iwecb *IncomingWebhookEventCreateBulk) Exec(ctx context.Context) error {
	_, err := iwecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iwecb *IncomingWebhookEventCreateBulk) ExecX(ctx context.Context) {
	if err := iwecb.Exec(ctx); err != nil {
		panic(err)
	}
}
